
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entry3;

	private global::Gtk.HPaned hpaned2;

	private global::Gtk.Label label2;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.HPaned hpaned3;

	private global::Gtk.Label label3;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.HPaned hpaned7;

	private global::Gtk.Label label4;

	private global::Gtk.Entry entry4;

	private global::Gtk.HPaned hpaned8;

	private global::Gtk.Label label5;

	private global::Gtk.Entry entry5;

	private global::Gtk.HPaned hpaned9;

	private global::Gtk.Label label6;

	private global::Gtk.Entry entry6;

	private global::Gtk.Button button1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView logTextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("RimWorld Mod Listing Generator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 80;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 0.95F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Page Title");
		this.hpaned1.Add(this.label1);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.label1]));
		w2.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.hpaned1.Add(this.entry3);
		this.vbox1.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned2 = new global::Gtk.HPaned();
		this.hpaned2.CanFocus = true;
		this.hpaned2.Name = "hpaned2";
		this.hpaned2.Position = 80;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.Xalign = 0.95F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Package?");
		this.hpaned2.Add(this.label2);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.label2]));
		w5.Resize = false;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = "";
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.checkbutton1.FocusOnClick = false;
		this.hpaned2.Add(this.checkbutton1);
		this.vbox1.Add(this.hpaned2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned3 = new global::Gtk.HPaned();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 80;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.Xalign = 0.95F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("AWS?");
		this.hpaned3.Add(this.label3);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned3[this.label3]));
		w8.Resize = false;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = "";
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.checkbutton2.FocusOnClick = false;
		this.hpaned3.Add(this.checkbutton2);
		this.vbox1.Add(this.hpaned3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned3]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned7 = new global::Gtk.HPaned();
		this.hpaned7.CanFocus = true;
		this.hpaned7.Name = "hpaned7";
		this.hpaned7.Position = 164;
		// Container child hpaned7.Gtk.Paned+PanedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Sensitive = false;
		this.label4.Name = "label4";
		this.label4.Xalign = 0.95F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Named Profile");
		this.label4.Justify = ((global::Gtk.Justification)(1));
		this.hpaned7.Add(this.label4);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.hpaned7[this.label4]));
		w11.Resize = false;
		// Container child hpaned7.Gtk.Paned+PanedChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.Sensitive = false;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.hpaned7.Add(this.entry4);
		this.vbox1.Add(this.hpaned7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned7]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned8 = new global::Gtk.HPaned();
		this.hpaned8.CanFocus = true;
		this.hpaned8.Name = "hpaned8";
		this.hpaned8.Position = 164;
		// Container child hpaned8.Gtk.Paned+PanedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Sensitive = false;
		this.label5.Name = "label5";
		this.label5.Xalign = 0.95F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("S3 Bucket");
		this.label5.Justify = ((global::Gtk.Justification)(1));
		this.hpaned8.Add(this.label5);
		global::Gtk.Paned.PanedChild w14 = ((global::Gtk.Paned.PanedChild)(this.hpaned8[this.label5]));
		w14.Resize = false;
		// Container child hpaned8.Gtk.Paned+PanedChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.Sensitive = false;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.hpaned8.Add(this.entry5);
		this.vbox1.Add(this.hpaned8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned8]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned9 = new global::Gtk.HPaned();
		this.hpaned9.CanFocus = true;
		this.hpaned9.Name = "hpaned9";
		this.hpaned9.Position = 164;
		// Container child hpaned9.Gtk.Paned+PanedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Sensitive = false;
		this.label6.Name = "label6";
		this.label6.Xalign = 0.95F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("CloudFront Distribution");
		this.label6.Justify = ((global::Gtk.Justification)(1));
		this.hpaned9.Add(this.label6);
		global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.hpaned9[this.label6]));
		w17.Resize = false;
		// Container child hpaned9.Gtk.Paned+PanedChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.Sensitive = false;
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.hpaned9.Add(this.entry6);
		this.vbox1.Add(this.hpaned9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned9]));
		w19.Position = 5;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("GO!");
		this.vbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button1]));
		w20.Position = 6;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.logTextView = new global::Gtk.TextView();
		this.logTextView.CanFocus = true;
		this.logTextView.Name = "logTextView";
		this.logTextView.Editable = false;
		this.logTextView.CursorVisible = false;
		this.logTextView.AcceptsTab = false;
		this.GtkScrolledWindow.Add(this.logTextView);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w22.Position = 7;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 401;
		this.DefaultHeight = 390;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.OnGo);
	}
}
